const Discord = require('discord.js')
const bot = new Discord.Client()

var prefix = "url?"

bot.login('')

bot.on('ready', function(){
    console.log('The bot is online!')
    bot.user.setActivity(`url\?help`)
})

bot.on('message', function(msg) {
    if(msg.content == 'What is my url?'){
        urlstuff(msg, msg.author)
    } else if(msg.content.startsWith(prefix)){
        const args = msg.content.slice(prefix.length).trim().split(/ +/g);
        const command = args.shift();

        if(command == 'help'){
            msg.channel.send('You can either type ``What is my url?`` or ``url?<mentions>`` \n For more information on a user, type ``url?info <mentions?>``');
        } else if(command == ''){
            msg.channel.send('Must include a mention.')
        } else if(command == 'info' && msg.guild != null && msg.guild.available){
            if(msg.mentions.users.size < 1){
                userinfo(msg, msg.author, msg.member);
            } else if(msg.mentions.users.size > 0){
                userinfo(msg, msg.mentions.users.first(), msg.mentions.members.first());
            }
        } else if(command == 'info'){
          msg.channel.send('This command can only be sent in a server.')
        } else if (msg.mentions.users.size < 1) {
            msg.channel.send('No mentions found, make sure you are actually mentioning someone.');
        } else if (msg.mentions.users.size > 0){
            var dismentions = msg.mentions.users
            dismentions.forEach(function(item, index, array){
                urlstuff(msg, item);
            })
        }
    }
})

function urlstuff(msg, items){
    msg.channel.send({embed: {
        color: Math.floor(Math.random() * 16777214) + 1,
        author: {
            name: items.username,
            icon_url: items.avatarURL
        },
        title: 'https://discordapp.com/users/' + items.id,
        url: 'https://discordapp.com/users/' + items.id
    }})
}

function userinfo(msg, items, memberstatus){
    if(memberstatus.colorRole != null){
        var color = memberstatus.displayColor
    } else {
        var color = 10070709
    }
    var dates = Date.now() - memberstatus.joinedAt
    var date = convertms(dates);
    msg.channel.send({ "embed": {
        "color": color,
        "timestamp": msg.createdTimestamp,
        "footer": {
            "icon_url": msg.author.avatarURL,
            "text": "Generated by: " + msg.author.username
        },
        "thumbnail": {
            "url": items.avatarURL
        },
        "author": {
            name: memberstatus.displayName,
            icon_url: items.avatarURL,
            "url": 'https://discordapp.com/users/' + items.id
        },
        "fields": [
            {
                "name": "Username:",
                "value": items.tag
            },
            {
                "name": "Profile Link:",
                "value": 'https://discordapp.com/users/' + items.id
            },
            {
                "name": "Created:",
                "value": items.createdAt.toString()
            },
            {
                "name": "Joined Server:",
                "value": date
            }
        ]
    }})
}


//https://gist.github.com/Erichain/6d2c2bf16fe01edfcffa
function convertms(milliseconds){
    var day, hour, minute, seconds;
    seconds = Math.floor(milliseconds / 1000);
    minute = Math.floor(seconds / 60);
    seconds = seconds % 60;
    hour = Math.floor(minute / 60);
    minute = minute % 60;
    day = Math.floor(hour / 24);
    hour = hour % 24;

  return day + ' days ' + hour + ' hours ' + minute + ' minutes ' + seconds + ' seconds ago';
}
