
module.exports = {
  userinfo: function(msg, items, memberstatus){
    userinfo(msg, items, memberstatus);
  },
  userinfodm: function(msg, items){
    userinfodm(msg, items);
  }
};

function userinfo(msg, items, memberstatus){
    if(memberstatus.colorRole != null){
        var color = memberstatus.displayColor
    } else {
        var color = 10070709
    }
    var dates = Date.now() - memberstatus.joinedAt
    var date = convertms(dates);
    msg.channel.send({ "embed": {
        "color": color,
        "timestamp": msg.createdTimestamp,
        "footer": {
            "icon_url": msg.author.avatarURL,
            "text": "Generated by: " + msg.author.username
        },
        "thumbnail": {
            "url": items.avatarURL
        },
        "author": {
            name: memberstatus.displayName,
            icon_url: items.avatarURL,
            "url": 'https://discordapp.com/users/' + items.id
        },
        "fields": [
            {
                "name": "Username:",
                "value": items.tag
            },
            {
                "name": "Profile Link:",
                "value": 'https://discordapp.com/users/' + items.id
            },
            {
                "name": "Created:",
                "value": items.createdAt.toString()
            },
            {
                "name": "Joined Server:",
                "value": date
            }
        ]
    }})
}

function userinfodm(msg, items){
    msg.channel.send({ "embed": {
        "color": 10070709,
        "timestamp": msg.createdTimestamp,
        "footer": {
            "icon_url": msg.author.avatarURL,
            "text": "Generated by: " + msg.author.username
        },
        "thumbnail": {
            "url": items.avatarURL
        },
        "author": {
            name: items.username,
            icon_url: items.avatarURL,
            "url": 'https://discordapp.com/users/' + items.id
        },
        "fields": [
            {
                "name": "Username:",
                "value": items.tag
            },
            {
                "name": "Profile Link:",
                "value": 'https://discordapp.com/users/' + items.id
            },
            {
                "name": "Created:",
                "value": items.createdAt.toString()
            }
        ]
    }})
}


//https://gist.github.com/Erichain/6d2c2bf16fe01edfcffa
function convertms(milliseconds){
    var day, hour, minute, seconds;
    seconds = Math.floor(milliseconds / 1000);
    minute = Math.floor(seconds / 60);
    seconds = seconds % 60;
    hour = Math.floor(minute / 60);
    minute = minute % 60;
    day = Math.floor(hour / 24);
    hour = hour % 24;

  return day + ' days ' + hour + ' hours ' + minute + ' minutes ' + seconds + ' seconds ago';
}
